#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarinhub_Actionbar.Resource", IsApplication=true)]

namespace Xamarinhub_Actionbar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Arrowup = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Downarrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int sidebar_icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int btnImgExpander = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int ivMenuImg = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int menuIconImgView = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int menuListView = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int titleBarLinearLayout = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int txtActionBarText = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int txtDescription = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int txtMnuText = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int txtPage = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MenuCustomLayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int AboutUs = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int Clients = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int ContactUs = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int Events = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int Help = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int Home = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int Products = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int Serivce = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int Solution = 2130968585;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
